// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTapLonNhom23.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221204132049_HoaDon")]
    partial class HoaDon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChuVu")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenChucVu")
                        .HasColumnType("TEXT");

                    b.HasKey("MaChuVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.DanhGia", b =>
                {
                    b.Property<string>("IDSp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiemDanhGia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GopY")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSp")
                        .HasColumnType("TEXT");

                    b.HasKey("IDSp");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.HoaDon", b =>
                {
                    b.Property<string>("IDKhachHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDSp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhuongThucTT")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SĐT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TongTien")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDKhachHang");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.KhachHang", b =>
                {
                    b.Property<string>("IDKhachHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SĐT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("TEXT");

                    b.HasKey("IDKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.Mau", b =>
                {
                    b.Property<string>("MaMau")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenMau")
                        .HasColumnType("TEXT");

                    b.HasKey("MaMau");

                    b.ToTable("Mau");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.NhanVien", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaChucVu")
                        .HasColumnType("TEXT");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueQuan")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SĐT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ten")
                        .HasColumnType("TEXT");

                    b.HasKey("MaID");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.QuanAo", b =>
                {
                    b.Property<string>("IDSp")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiaTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaMau")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSize")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThuongHieu")
                        .HasColumnType("TEXT");

                    b.HasKey("IDSp");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaSize");

                    b.ToTable("QuanAo");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.Size", b =>
                {
                    b.Property<string>("MaSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSize")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSize");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.NhanVien", b =>
                {
                    b.HasOne("BaiTapLon_Nhom23.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaChucVu");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("BaiTapLon_Nhom23.Models.QuanAo", b =>
                {
                    b.HasOne("BaiTapLon_Nhom23.Models.Mau", "Mau")
                        .WithMany()
                        .HasForeignKey("MaMau");

                    b.HasOne("BaiTapLon_Nhom23.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("MaSize");

                    b.Navigation("Mau");

                    b.Navigation("Size");
                });
#pragma warning restore 612, 618
        }
    }
}
